name: Java CI con pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Clonar el repositorio
      - name: Clonar repositorio
        uses: actions/checkout@v3

      # 2️⃣ Instalar Java 17
      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3️⃣ Descargar JUnit 5 y dependencias
      - name: Descargar JUnit 5
        run: |
          cd Calculadora
          wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-api/5.11.0/junit-jupiter-api-5.11.0.jar
          wget https://repo1.maven.org/maven2/org/junit/jupiter/junit-jupiter-engine/5.11.0/junit-jupiter-engine-5.11.0.jar
          wget https://repo1.maven.org/maven2/org/apiguardian/apiguardian-api/1.1.2/apiguardian-api-1.1.2.jar
          wget https://repo1.maven.org/maven2/org/opentest4j/opentest4j/1.3.0/opentest4j-1.3.0.jar

      # 4️⃣ Compilar el código y los tests
      - name: Compilar código
        run: |
          cd Calculadora
          javac -cp "src/main/java:src/test/java:junit-jupiter-api-5.11.0.jar:apiguardian-api-1.1.2.jar:opentest4j-1.3.0.jar" \
            src/main/java/com/uttec/Calculadora/Calculadora.java \
            src/test/java/com/uttec/Calculadora/CalculadoraTest.java

      # 5️⃣ Ejecutar pruebas con JUnit 5
      - name: Ejecutar pruebas
        run: |
          cd Calculadora
          java -cp "src/main/java:src/test/java:junit-jupiter-api-5.11.0.jar:junit-jupiter-engine-5.11.0.jar:apiguardian-api-1.1.2.jar:opentest4j-1.3.0.jar" \
            org.junit.platform.console.ConsoleLauncher --scan-class-path
