name: Java CI con pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Descargar JUnit 5 Standalone
        run: |
          cd Calculadora
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.2/junit-platform-console-standalone-1.11.2.jar

      - name: Compilar código
        run: |
          cd Calculadora
          javac -cp "src/main/java:junit-platform-console-standalone-1.11.2.jar" \
            src/main/java/com/uttec/Calculadora/Calculadora.java \
            src/test/java/com/uttec/Calculadora/CalculadoraTest.java

      - name: Ejecutar pruebas
        run: |
          cd Calculadora
          java -jar junit-platform-console-standalone-1.11.2.jar \
            --class-path src/main/java:src/test/java \
            --scan-class-path
