name: Java CI con pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Descargar JUnit 5 Standalone
        run: |
          cd Calculadora
          wget https://repo1.maven.org/maven2/org/junit/platform/junit-platform-console-standalone/1.11.2/junit-platform-console-standalone-1.11.2.jar

      - name: Compilar código
        run: |
          cd Calculadora
          javac -cp "src/main/java:junit-platform-console-standalone-1.11.2.jar" \
            src/main/java/com/uttec/Calculadora/Calculadora.java \
            src/test/java/com/uttec/Calculadora/CalculadoraTest.java

      - name: Ejecutar pruebas
        run: |
          cd Calculadora
          java -jar junit-platform-console-standalone-1.11.2.jar \
            --class-path src/main/java:src/test/java \
            --scan-class-path

      - name: Notificar en Slack si tiene éxito
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"✅ ¡Éxito! Todas las pruebas de la Calculadora Java pasaron. Revisa los detalles en GitHub Actions: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notificar en Slack si falla
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data '{"text":"❌ Fallo en el pipeline de la Calculadora Java. Revisa los detalles en GitHub Actions: https://github.com/${GITHUB_REPOSITORY}/actions/runs/${GITHUB_RUN_ID}"}' \
          ${{ secrets.SLACK_WEBHOOK_URL }}
