name: Java CI con pruebas

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Instalar Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Descargar JUnit y Hamcrest
        run: |
          wget https://repo1.maven.org/maven2/junit/junit/4.13.2/junit-4.13.2.jar
          wget https://repo1.maven.org/maven2/org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar

      - name: Compilar código
        run: javac -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar \
                src/main/java/calculadora/Calculadora.java \
                src/test/java/calculadora/CalculadoraTest.java


      - name: Ejecutar pruebas
        run: java -cp .:junit-4.13.2.jar:hamcrest-core-1.3.jar:src/main/java:src/test/java \
            org.junit.runner.JUnitCore calculadora.CalculadoraTest
